// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package q

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"go.uber.org/zap"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addUserToWhitelistStmt, err = db.PrepareContext(ctx, addUserToWhitelist); err != nil {
		return nil, fmt.Errorf("error preparing query AddUserToWhitelist: %w", err)
	}
	if q.countGroupsStmt, err = db.PrepareContext(ctx, countGroups); err != nil {
		return nil, fmt.Errorf("error preparing query CountGroups: %w", err)
	}
	if q.deleteUserFromWhitelistStmt, err = db.PrepareContext(ctx, deleteUserFromWhitelist); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserFromWhitelist: %w", err)
	}
	if q.getDhashFromFileUidStmt, err = db.PrepareContext(ctx, getDhashFromFileUid); err != nil {
		return nil, fmt.Errorf("error preparing query GetDhashFromFileUid: %w", err)
	}
	if q.getGroupMarsCountStmt, err = db.PrepareContext(ctx, getGroupMarsCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetGroupMarsCount: %w", err)
	}
	if q.getMarsInfoStmt, err = db.PrepareContext(ctx, getMarsInfo); err != nil {
		return nil, fmt.Errorf("error preparing query GetMarsInfo: %w", err)
	}
	if q.incrementGroupStatStmt, err = db.PrepareContext(ctx, incrementGroupStat); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementGroupStat: %w", err)
	}
	if q.incrementMarsInfoStmt, err = db.PrepareContext(ctx, incrementMarsInfo); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementMarsInfo: %w", err)
	}
	if q.isUserInWhitelistStmt, err = db.PrepareContext(ctx, isUserInWhitelist); err != nil {
		return nil, fmt.Errorf("error preparing query IsUserInWhitelist: %w", err)
	}
	if q.listMarsInfoByGroupStmt, err = db.PrepareContext(ctx, listMarsInfoByGroup); err != nil {
		return nil, fmt.Errorf("error preparing query ListMarsInfoByGroup: %w", err)
	}
	if q.listSimilarPhotosStmt, err = db.PrepareContext(ctx, listSimilarPhotos); err != nil {
		return nil, fmt.Errorf("error preparing query ListSimilarPhotos: %w", err)
	}
	if q.setMarsWhitelistStmt, err = db.PrepareContext(ctx, setMarsWhitelist); err != nil {
		return nil, fmt.Errorf("error preparing query SetMarsWhitelist: %w", err)
	}
	if q.upsertDhashStmt, err = db.PrepareContext(ctx, upsertDhash); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertDhash: %w", err)
	}
	if q.upsertMarsInfoStmt, err = db.PrepareContext(ctx, upsertMarsInfo); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMarsInfo: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addUserToWhitelistStmt != nil {
		if cerr := q.addUserToWhitelistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserToWhitelistStmt: %w", cerr)
		}
	}
	if q.countGroupsStmt != nil {
		if cerr := q.countGroupsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countGroupsStmt: %w", cerr)
		}
	}
	if q.deleteUserFromWhitelistStmt != nil {
		if cerr := q.deleteUserFromWhitelistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserFromWhitelistStmt: %w", cerr)
		}
	}
	if q.getDhashFromFileUidStmt != nil {
		if cerr := q.getDhashFromFileUidStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDhashFromFileUidStmt: %w", cerr)
		}
	}
	if q.getGroupMarsCountStmt != nil {
		if cerr := q.getGroupMarsCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGroupMarsCountStmt: %w", cerr)
		}
	}
	if q.getMarsInfoStmt != nil {
		if cerr := q.getMarsInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMarsInfoStmt: %w", cerr)
		}
	}
	if q.incrementGroupStatStmt != nil {
		if cerr := q.incrementGroupStatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementGroupStatStmt: %w", cerr)
		}
	}
	if q.incrementMarsInfoStmt != nil {
		if cerr := q.incrementMarsInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementMarsInfoStmt: %w", cerr)
		}
	}
	if q.isUserInWhitelistStmt != nil {
		if cerr := q.isUserInWhitelistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isUserInWhitelistStmt: %w", cerr)
		}
	}
	if q.listMarsInfoByGroupStmt != nil {
		if cerr := q.listMarsInfoByGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMarsInfoByGroupStmt: %w", cerr)
		}
	}
	if q.listSimilarPhotosStmt != nil {
		if cerr := q.listSimilarPhotosStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSimilarPhotosStmt: %w", cerr)
		}
	}
	if q.setMarsWhitelistStmt != nil {
		if cerr := q.setMarsWhitelistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setMarsWhitelistStmt: %w", cerr)
		}
	}
	if q.upsertDhashStmt != nil {
		if cerr := q.upsertDhashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertDhashStmt: %w", cerr)
		}
	}
	if q.upsertMarsInfoStmt != nil {
		if cerr := q.upsertMarsInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMarsInfoStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	logger                      *zap.Logger
	SlowQueryThreshold          time.Duration
	txID                        string
	LogRawSqlString             bool
	LogArgument                 bool
	tx                          *sql.Tx
	addUserToWhitelistStmt      *sql.Stmt
	countGroupsStmt             *sql.Stmt
	deleteUserFromWhitelistStmt *sql.Stmt
	getDhashFromFileUidStmt     *sql.Stmt
	getGroupMarsCountStmt       *sql.Stmt
	getMarsInfoStmt             *sql.Stmt
	incrementGroupStatStmt      *sql.Stmt
	incrementMarsInfoStmt       *sql.Stmt
	isUserInWhitelistStmt       *sql.Stmt
	listMarsInfoByGroupStmt     *sql.Stmt
	listSimilarPhotosStmt       *sql.Stmt
	setMarsWhitelistStmt        *sql.Stmt
	upsertDhashStmt             *sql.Stmt
	upsertMarsInfoStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		logger:                      q.logger,
		SlowQueryThreshold:          q.SlowQueryThreshold,
		txID:                        fmt.Sprintf("%p", tx),
		LogRawSqlString:             q.LogRawSqlString,
		LogArgument:                 q.LogArgument,
		tx:                          tx,
		addUserToWhitelistStmt:      q.addUserToWhitelistStmt,
		countGroupsStmt:             q.countGroupsStmt,
		deleteUserFromWhitelistStmt: q.deleteUserFromWhitelistStmt,
		getDhashFromFileUidStmt:     q.getDhashFromFileUidStmt,
		getGroupMarsCountStmt:       q.getGroupMarsCountStmt,
		getMarsInfoStmt:             q.getMarsInfoStmt,
		incrementGroupStatStmt:      q.incrementGroupStatStmt,
		incrementMarsInfoStmt:       q.incrementMarsInfoStmt,
		isUserInWhitelistStmt:       q.isUserInWhitelistStmt,
		listMarsInfoByGroupStmt:     q.listMarsInfoByGroupStmt,
		listSimilarPhotosStmt:       q.listSimilarPhotosStmt,
		setMarsWhitelistStmt:        q.setMarsWhitelistStmt,
		upsertDhashStmt:             q.upsertDhashStmt,
		upsertMarsInfoStmt:          q.upsertMarsInfoStmt,
	}
}

func (q *Queries) logQuery(sqlString, query string, params []zap.Field, err error, start time.Time) {
	if q.logger == nil {
		return
	}

	duration := time.Since(start)
	fields := make([]zap.Field, 0, len(params)+4)
	fields = append(fields,
		zap.Time("ts", start),
		zap.String("query_name", query),
	)
	if q.LogRawSqlString {
		fields = append(fields, zap.String("sql", sqlString))
	}
	if q.txID != "" {
		fields = append(fields, zap.String("txID", q.txID))
	}
	fields = append(fields, params...)
	fields = append(fields, zap.Duration("duration", duration))
	if err != nil {
		fields = append(fields, zap.Error(err))
	}

	if q.SlowQueryThreshold > 0 && duration > q.SlowQueryThreshold {
		q.logger.Warn("slow query", fields...)
		return
	}
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		q.logger.Error("query failed", fields...)
		return
	}
	q.logger.Info("query", fields...)
}

func zapNullString(key string, v sql.NullString) zap.Field {
	if v.Valid {
		return zap.String(key, v.String)
	}
	return zap.Any(key, nil)
}

func zapNullBool(key string, v sql.NullBool) zap.Field {
	if v.Valid {
		return zap.Bool(key, v.Bool)
	}
	return zap.Any(key, nil)
}

func zapNullInt32(key string, v sql.NullInt32) zap.Field {
	if v.Valid {
		return zap.Int32(key, v.Int32)
	}
	return zap.Any(key, nil)
}

func zapNullInt64(key string, v sql.NullInt64) zap.Field {
	if v.Valid {
		return zap.Int64(key, v.Int64)
	}
	return zap.Any(key, nil)
}

func zapNullFloat64(key string, v sql.NullFloat64) zap.Field {
	if v.Valid {
		return zap.Float64(key, v.Float64)
	}
	return zap.Any(key, nil)
}

func zapNullTime(key string, v sql.NullTime) zap.Field {
	if v.Valid {
		return zap.Time(key, v.Time)
	}
	return zap.Any(key, nil)
}

type zapObj interface {
	ZapObject(name string) zap.Field
}

func zapNullOf[T zapObj](name string, optObj sql.Null[T]) zap.Field {
	if optObj.Valid {
		return optObj.V.ZapObject(name)
	}
	return zap.Any(name, nil)
}
