// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package q

type FuidToDhash struct {
	Fuid  string `json:"fuid"`
	Dhash []byte `json:"dhash"`
}

type GroupUserInWhitelist struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

type MarsGroupStat struct {
	GroupID    int64 `json:"group_id"`
	ImageCount int64 `json:"image_count"`
}

type MarsInfo struct {
	GroupID     int64  `json:"group_id"`
	PicDhash    []byte `json:"pic_dhash"`
	Count       int64  `json:"count"`
	LastMsgID   int64  `json:"last_msg_id"`
	InWhitelist int64  `json:"in_whitelist"`
}

type MarsStatMetum struct {
	Key   string `json:"key"`
	Value int64  `json:"value"`
}
